const actions = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_SIGNUP: 'USER_SIGNUP',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  // JOB ACTION
  UPLOAD_POST: 'UPLOAD_POST',
  UPLOAD_POST_SUCCESS: 'UPLOAD_POST_SUCCESS',
  GET_ALL_JOB: 'GET_ALL_JOB',
  GET_ALL_JOB_SUCCESS: 'GET_ALL_JOB_SUCCESS',
  DELETE_JOB: 'DELETE_JOB',
  EDIT_JOB: 'EDIT_JOB',
  EDIT_JOB_SUCCESS: 'EDIT_JOB_SUCCESS',
  // GET INFO USER
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  DELET_USER_INFO: 'DELET_USER_INFO',
  EDIT_USER: 'EDIT_USER',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',


  // GET ACCOUNT
  GET_LIST_USER: 'GET_LIST_USER',
  GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
  GET_LIST_USER_REC: 'GET_LIST_USER_REC',
  GET_LIST_USER_REC_SUCCESS: 'GET_LIST_USER_REC_SUCCESS',
  FILTER_USER: "FILTER_USER",
  FILTER_USER_USERNAME: 'FILTER_USER_USERNAME',
  // GET LIST RECRUITMENT
  GET_LIST_RECRUITMENT: 'GET_LIST_RECRUITMENT',
  GET_LIST_RECRUITMENT_SUCCESS: 'GET_LIST_RECRUITMENT_SUCCESS',
  // VERIFY CANDIDATE
  VERIFY_CANDIDATE: 'VERIFY_CANDIDATE',
  VERIFY_CANDIDATE_SUCCESS: 'VERIFY_CANDIDATE_SUCCESS',

  // FeedBack Job
  APPROVE_TO_JOB: 'APPROVE_TO_JOB',
  APPROVE_TO_JOB_SUCCESS: 'APPROVE_TO_JOB_SUCCESS',
  REJECT_TO_JOB: 'REJECT_TO_JOB',
  REJECT_TO_JOB_SUCCESS: 'REJECT_TO_JOB_SUCCESS',
  APPLY_TO_JOB: 'APPLY_TO_JOB',
  APPLY_TO_JOB_SUCCESS: 'APPLY_TO_JOB_SUCCESS',
  // Checkout
  ADD_COINS: 'ADD_COINS',
  UPGRADE_VIP: 'UPGRADE_VIP',
  REMOVE_COINS: 'REMOVE_COINS',
  // Products 
  GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
  GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  EDIT_PRODUCT:'EDIT_PRODUCT',
  FILTER_CATEGORY:'FILTER_CATEGORY',
  SEARCH_NAME_PRODUCT:'SEARCH_NAME_PRODUCT',
  FILTER_PRICE_PRODUCT:'FILTER_PRICE_PRODUCT',
  // Get list categories
  GET_LIST_CATEGORIES: 'GET_LIST_CATEGORIES',
  GET_LIST_CATEGORIES_SUCCESS: 'GET_LIST_CATEGORIES_SUCCESS',
  EDIT_CATEGORIES: 'EDIT_CATEGORIES',
  ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  PAGINATION_DATA: 'PAGINATION_DATA',
  ADD_CART: 'ADD_CART',
  GET_CART: 'GET_CART',
  REMOVE_CART: 'REMOVE_CART',
  UPDATE_CART: 'UPDATE_CART',
  CLEAR_CART: 'CLEAR_CART',
  // GET BRANCH

}
export default actions;